// ReSharper disable InconsistentNaming
namespace GirlAloneServer.Core.Model.Enums;

public enum RewardType
{
    NONE = -1,
    Intimacy,
    Sociability,
    GiveSociability,
    GiveIntimacy,
    GiveFeeling,
    Gold,
    Gem,
    DogExp,
    CatExp,
    ITEM_QUEST,
    ITEM_COSTUME,
    ITEM_FOOD,
    ITEM_GIFT,
    ITEM_FURNITURE,
    ITEM_PET,
    ITEM_PETFOOD_DOG,
    ITEM_PETFOOD_CAT,
    Ticket,
    AlbaBonusGold,
    DialogChargeTime,
    Ruby,
    TogetherAlbaBonusGold,
    DateBounsIntimacy,
    PremiumBounsScore,
    HammerBounsCoolTime,
    HammerBounsActiveTime,
    DialogAds,
    Conversation,
    FeverTime,
    TogetherBonusItemScore,
    AlbaBuildingExp,
    Hammer,
    Costume,
    END
}